apiVersion: v1
entries:
  PostDock:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2020-02-23T09:37:35.517585651-05:00"
    description: Postdock chart for kubernetes
    digest: 13e58361f9de238feb4f18c15f83ef3ec477455cf414817a902c4da1ae0f0be0
    home: https://github.com/elfelip/PostDock
    icon: https://raw.githubusercontent.com/elfelip/PostDock/master/artwork/logo.png
    keywords:
    - database
    - postgres
    - postgresql
    - postdock
    - cluster
    maintainers:
    - email: elfelip@yahoo.com
      name: Philippe Gauthier
    name: PostDock
    sources:
    - https://github.com/elfelip/PostDock
    urls:
    - PostDock-1.2.0.tgz
    version: 1.2.0
generated: "2020-02-23T09:37:35.515464654-05:00"
