apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-data-mysystem-db-node-1
  labels:
    system: mysystem-db
    node: node-1
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: /opt/local-path-provisioner/db-data-mysystem-db-node-1
  # awsElasticBlockStore:
  #   fsType: ext4
  #   volumeID: vol-xxxxxxx